### ISSUE TITLE
Text Area is broken

### ISSUE THREAD

**Issue by TheGoodwin** [ShiiFu/decode#1]
The text area pass through the buttons on the right.
It should be width-blocked.
![issue](https://cloud.githubusercontent.com/assets/17168076/17138060/c7a369de-533e-11e6-8219-93f36e42da38.png)

**Comment by ShiiFu** [comment]
Thanks

Corrected by [this commit](https://github.com/ShiiFu/decode/commit/7fc4aac1fd03639bfd2570246bd9177fa50ee6b5)
